#!/bin/bash

MSG="$(cat $1)"
PATTERN="#[0-9]*"
ower="jerffesongd"
repo="gerencia-config-mudanca"
isDoing=false

if [[ $MSG =~ $PATTERN ]];then
        echo "[*] Comtém número de issue [*]"
else
        echo "Mensagem do commit NÂO possui número de issue!"
        exit 1
fi

numberIssue="$(echo $MSG | grep -o -E '[0-9]+')"

url="https://api.github.com/repos/${ower}/${repo}/issues/${numberIssue}/labels"

for l in $(curl -u jerffesongd:e8a0f7d2e458eaa38c03ce8dabdb7f8f9c34b6ad $url | jq '.[] .name')

do

    if [[ ${l//\"/''} == *"doing"* ]]; then
        isDoing=true
    fi
    
done


if [ "$isDoing" = false ]; then
	echo "Issue NÂO esta em DOING"
    exit 1
else
    echo "[*] Issue esta em DOING"
    exit 0
fi