#!/bin/bash

MSG="$(git show --format='%B' -s $SHA1)"
ower="jerffesongd"
repo="gerencia-config-mudanca"

numberIssue="$(echo $MSG | grep -o -E '[0-9]+')"

COMMENT=""
COMMENT="$COMMENT$(date) \n"
COMMENT="$COMMENT$(git config user.name) \n"
COMMENT="$COMMENT$(git diff --name-only HEAD HEAD~1) \n"
COMMENT="$COMMENT$MSG"
COMMENT="$(echo $COMMENT | tr -d '\n')"

curl -s -o nul -X POST -H "Accept: application/vnd.github.v3+json " -H "Authorization: token 762376386538e1264a17fedca2dfdb91ff6cac9b" https://api.github.com/repos/${ower}/${repo}/issues/$numberIssue/comments --data "{ \"body\":\"$COMMENT\"}"