#!/bin/bash

MSG="$(git show --format='%B' -s $SHA1)"
ower="jerffesongd"
repo="gerencia-config-mudanca"

numberIssue="$(echo $MSG | grep -o -E '[0-9]+')"

COMMENT=""
COMMENT="$COMMENT$(date) \n"
COMMENT="$COMMENT$(git config user.name) \n"
COMMENT="$COMMENT$(git diff --name-only HEAD HEAD~1) \n"
COMMENT="$COMMENT$MSG"
COMMENT="$(echo $COMMENT | tr -d '\n')"


curl -X POST -H "Accept: application/vnd.github.v3+json " -H "Authorization: token e8a0f7d2e458eaa38c03ce8dabdb7f8f9c34b6ad" https://api.github.com/repos/${ower}/${repo}/issues/$numberIssue/comments --data "{ \"body\":\"$COMMENT\"}" > /dev/null